/* -*-Java-*- */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Important information:
 * THIS JAVA SOURCE FILE HAS BEEN AUTOMATICALLY GENERATED by the public domain
 * JB tool (see README.html for details) from template based on JB.
 */

package pl.edu.agh.icsr.janet.natives.c;

public
abstract
class TokenTypes {

public static final int EOF = 0;

public static final int tokenmin = 257;
public static final int tokenmax = 263;

public static final int YYNONE = -1;
public static final int YYEOF = EOF;

public static final int LEX_ERROR = 257;
public static final int EPSILON = 258;
public static final int CTEXT = 259;
public static final int CSTATEMENT_CHAR = 260;
public static final int JAVA_EXPRESSION = 261;
public static final int JAVA_STATEMENTS = 262;
public static final int JAVA_ENCLOSED_STATEMENTS = 263;


public static final String yytname[] = yytnameTableCreator();

private static final String[] yytnameTableCreator() {
  final String yytname[] = {
   "$","error","$undefined.","LEX_ERROR",
"EPSILON","CTEXT","CSTATEMENT_CHAR","JAVA_EXPRESSION","JAVA_STATEMENTS","JAVA_ENCLOSED_STATEMENTS",
"'`'","'('","')'","'['","']'","'{'","'}'","Start","@1","Outer","Goal","CStatementsWithJavaTail",
"CStatements_opt","CStatements","CStatement","@2","@3","BrokenJavaStatement",
"JavaBegin","JavaEnd","CBlock","@4","@5", null

  };
  return yytname;
}



};
