/* -*-Java-*- */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

/* Important information:
 * THIS JAVA SOURCE FILE HAS BEEN AUTOMATICALLY GENERATED by the public domain
 * JB tool (see README.html for details) from template based on JB.
 */

package pl.edu.agh.icsr.janet.natives.c;

public
abstract
class TokenTypes {

public static final int EOF = 0;

public static final int tokenmin = 257;
public static final int tokenmax = 263;

public static final int YYNONE = -1;
public static final int YYEOF = EOF;

public static final int LEX_ERROR = 257;
public static final int EPSILON = 258;
public static final int CTEXT = 259;
public static final int CSTATEMENT_CHAR = 260;
public static final int JAVA_EXPRESSION = 261;
public static final int JAVA_STATEMENTS = 262;
public static final int JAVA_ENCLOSED_STATEMENTS = 263;


public static final String tokennames[] = {
"LEX_ERROR",
"EPSILON",
"CTEXT",
"CSTATEMENT_CHAR",
"JAVA_EXPRESSION",
"JAVA_STATEMENTS",
"JAVA_ENCLOSED_STATEMENTS",
null
};

public static String tokenname(Integer t)
{return tokenname(t==null?EOF:t.intValue());}

public static String tokenname(int t)
{
    if(t >= tokenmin && t <= tokenmax) {
        return tokennames[t - tokenmin];
    } else if(t > 0 && t <= 255) {
        return "'" + String.valueOf((char)t) + "'";
    } else if(t == EOF) {
        return "EOF";
    } else {
        return "$undefined$";
    }
}

//////////////////////////////////////////////////

public static final int nontermmin = 264;
public static final int nontermmax = 279;

public static final int nt_Start = 264;
public static final int nt_at_1 = 265;
public static final int nt_Outer = 266;
public static final int nt_Goal = 267;
public static final int nt_CStatementsWithJavaTail = 268;
public static final int nt_CStatements_opt = 269;
public static final int nt_CStatements = 270;
public static final int nt_CStatement = 271;
public static final int nt_at_2 = 272;
public static final int nt_at_3 = 273;
public static final int nt_BrokenJavaStatement = 274;
public static final int nt_JavaBegin = 275;
public static final int nt_JavaEnd = 276;
public static final int nt_CBlock = 277;
public static final int nt_at_4 = 278;
public static final int nt_at_5 = 279;


public static final String nontermnames[] = {
"Start",
"@1",
"Outer",
"Goal",
"CStatementsWithJavaTail",
"CStatements_opt",
"CStatements",
"CStatement",
"@2",
"@3",
"BrokenJavaStatement",
"JavaBegin",
"JavaEnd",
"CBlock",
"@4",
"@5",
null
};

public static String nontermname(int t)
{
    if(t >= nontermmin && t <= nontermmax) {
        return nontermnames[t - nontermmin];
    } else {
        return "$undefined$";
    }
}

//////////////////////////////////////////////////
};
